### PR TITLE
Schema validation

### PR DESCRIPTION
**Pull request by accu-clw**
image

Investigate the use of the provided [JSON Schema](https://docs.postmen.com/downloads/postmen-schema.tar.gz), from https://docs.postmen.com/.

### CODE REVIEW

**Comment by accu-clw** [comment]
:warning: `eei-aes.json` is missing.

**Comment by haoyangyuying** [comment]
Hello from postmen, we really appreciate your checking. 

> schema for "eei_aes.json" appears to be missing

You are correct, this file is named as eei.json wrongly. Already fixed 🚀  .

> schemas for address validation

Yes, address validation is still in testing, will be released in the near future. Let's keep in touch~

**Comment by accu-clw** [comment]
> > schema for "eei_aes.json" appears to be missing
> 
> You are correct, this file is named as eei.json wrongly. Already fixed  .

@haoyangyuying :wave: 
Thanks for reaching out and confirming. Will the updates be published soon?

Do you have a public repository for the schemas? Ideally, we would just be able to pull changes from there ourselves.

**Comment by haoyangyuying** [comment]
@accu-clw 
> Will the updates be published soon?
This was published yesterday, please try to download and update. 

> Do you have a public repository for the schemas?
We do not have public repo for schemas now, and we are thinking about release log to notice these changes in the future.

**Review by Zici — APPROVED** [review]

**Pull request merged**
